[package]
name = "tlsn-examples"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tlsn-core.workspace = true
tlsn-tls-core.workspace = true
tlsn-tls-client.workspace = true
notary-server = { path = "../../notary-server" }
mpz-core.workspace = true
tlsn-prover = { workspace = true, features = ["tracing"] }
tlsn-verifier.workspace = true
tokio-tungstenite = { version = "0.21.0",features = ["native-tls"]}

p256 = { workspace = true, features = ["ecdsa"] }
elliptic-curve = { version = "0.13.5", features = ["pkcs8"] }
webpki-roots.workspace = true

rustls = { version = "0.21" }
rustls-pemfile = { version = "1.0.2" }
tokio-rustls = { version = "0.24.1" }
async-tls = { version = "0.12", default-features = false, features = [
    "client",
] }
futures.workspace = true
tokio = { workspace = true, features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "net",
    "io-std",
    "fs",
] }
tokio-util.workspace = true
hyper = { version = "1.1", features = ["client", "http1"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
chrono = "0.4"

tracing.workspace = true
tracing-subscriber.workspace = true
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0"
eyre = "0.6.8"
dotenv = "0.15.0"

warp={version = "0.3.6", features=["tls"] }
validator = { version = "0.16", features = ["derive"] }
web3 = "0.19.0"
hex-literal = "0.4"
rust-crypto = "0.2.36"
rand = "0.8.5"
hex = "0.4.3"
base64 = "0.13"
futures-util = "0.3.29"
reqwest = { version = "0.11", features = ["json"] }

[[example]]
name = "simple_prover"
path = "simple/simple_prover.rs"

[[example]]
name = "simple_websocket"
path = "simple/simple_websocket.rs"

[[example]]
name = "simple_verifier"
path = "simple/simple_verifier.rs"

[[example]]
name = "twitter_dm"
path = "twitter/twitter_dm.rs"

[[example]]
name = "discord_dm"
path = "discord/discord_dm.rs"

[[example]]
name = "discord_dm_verifier"
path = "discord/discord_dm_verifier.rs"
